documentation/testnet/getting_started/00_overview.md

This PR adds a disclaimer that Aleo Testnet I is not production ready and is a trusted testnet.

Add disclaimer for Aleo Testnet I

---

documentation/developer/language/04_arrays_and_tuples.md

This is based on some discussions on Slack.
I added a section near the beginning that clarifies what defines an array type. Please confirm that it is correct.
I also edited some text about multidimensional arrays, to remove the restriction to primitive value elements and to explain that multidimensional arrays are simply arrays of arrays. Please confirm that this is correct.

Clarify array types.

---

documentation/testnet/getting_started/01_installation.md

This PR updates the build and usage guides for snarkOS to match the snarkOS main `README.md`.

Update snarkOS installation docs

---

documentation/developer/additional_material/00_style.md
documentation/developer/language/00_flying_tour.md
documentation/developer/language/01_layout.md
documentation/developer/language/03_types.md
documentation/developer/language/04_arrays_and_tuples.md
documentation/developer/language/07_functions.md
documentation/developer/language/12_tests.md
documentation/developer/toy_examples/03_pedersen_hash.md

Will be up to date with Leo version 1.0.8

Fix all developer code examples

---

documentation/aleo/concepts/01_programs.md
documentation/developer/cli/06_setup.md
documentation/developer/cli/09_login.md
documentation/developer/cli/10_logout.md
documentation/developer/getting_started/00_overview.md
documentation/developer/getting_started/03_syntax.md
documentation/developer/getting_started/04_cli.md

Following https://github.com/AleoHQ/leo/issues/684.
- removes last occurrences of static function
- improves docs for some cli commands
- adds skip-key-check option in leo setup

[Docs] Adds small changes to CLI docs and formatting

---

documentation/developer/language/00_flying_tour.md
documentation/developer/language/02_variables.md
documentation/developer/language/04_arrays_and_tuples.md
documentation/developer/language/07_functions.md
documentation/developer/language/08_inputs.md
documentation/developer/language/09_circuits.md

Update Leo developer docs for DP2

---

documentation/aleo/concepts/01_programs.md
documentation/developer/language/00_flying_tour.md
documentation/developer/language/01_layout.md
documentation/developer/language/04_arrays_and_tuples.md
documentation/developer/language/07_functions.md
documentation/developer/language/09_circuits.md
documentation/developer/toy_examples/03_pedersen_hash.md

Went through almost every code example on every page and ran it with latest master of Leo.
- Programming model
- Toy Examples: Digital Assets

Fixes all code examples to be executable

---

documentation/developer/language/04_arrays_and_tuples.md

I believe the final decision was that 'from' index is inclusive, 'to' index exclusive.

Update description and examples of array ranges

---

documentation/developer/language/13_lexical.md

This is not in the ABNF grammar.

Remove keyword

---

documentation/developer/additional_material/03_contributing.md

Is there anything I'm missing here?
Does everything seem clear?

update contributing docs

---

documentation/developer/language/02_variables.md

Closes https://github.com/AleoHQ/leo/issues/1147

Adds global constants

---

documentation/developer/language/00_flying_tour.md

Change register type from u32 to bool﻿

Fix input type for square example

---

documentation/developer/language/04_arrays_and_tuples.md

Closes https://github.com/AleoHQ/leo/issues/1320

Adds arrays without size section to the arrays doc page

---

documentation/advanced/posw/03_mining.md

A missing parentheses is added

Fix a typo

---

documentation/aleo/07_abnf.md

These were found while writing/generating a formal parser from the grammar.
Signed-off-by: Eric McCarthy <bendyarm@gmail.com>

Fix a few typos

---

documentation/leo/02_hello.md
documentation/leo/03_language.md

Uncovered while reviewing and testing the documentation.

Some fixes/updates.

---

documentation/testnet/public_endpoints/15_node_address.md

Modify the title to `Node Address` from `Latest Height` for Node_address page
@collinc97 Check it pls..
FYI.. @howardwu 
Signed-off-by: CrypticDriver <107245892+CrypticDriver@users.noreply.github.com>

Correct the page title and sub label

---

documentation/leo/04_operators.md

Fix some code errors.
Remove the commented out `` table rows because somehow they were still showing up in some form on the web pages.
interface => struct

Updates to Leo ops chapter.

---

documentation/aleo/08_tooling.md
documentation/leo/01_installation.md
documentation/leo/03_language.md

Adds documentation for inline functions and visibility in Leo.

Feature: Leo function inline and visibility

---

documentation/00_getting_started.md

add whats new header to docs

---

documentation/testnet/getting_started/02_deploy_and_execute.md

@collinc97 can I get your 👀 and approval on this?

fixing some links and the faucet text on 02_deploy_and_execute.md

---

documentation/testnet/getting_started/03_deploy_and_execute_demo.md

Adds execute command to Demo so that folks can learn to execute and application instead of just deploy it

Adding to demo

---

documentation/aleo/04_opcodes.md
documentation/leo/04_operators.md

fixes https://github.com/AleoHQ/aleo/issues/520 and reformats all opcode tables

Fix eq iseq opcode destination register columns

---

documentation/concepts/03A_transaction_fees.md

Aligned with the new transaction fee requirement across all transaction types and not just Deploys, this new section of Aleo Concepts breaks down transaction fees by type, size, and denomination.

Adding tx fees to Aleo Concepts

---

documentation/00_overview.md
documentation/concepts/03A_transaction_fees.md

Adds transaction fees under transactions

Add transaction fees under transactions

---

.github/workflows/ci-branches.yml
documentation/aleo/04_opcodes.md
documentation/leo/04_operators.md

Matches https://github.com/AleoHQ/snarkVM/pull/1576.

Update Aleo instructions and Leo for commits and hashes.

---

documentation/leo/08_auction.md

fix links for generating aleo accounts

---

documentation/aleo/04_opcodes.md

Per [issue 183](https://github.com/AleoHQ/welcome/issues/183), remove all mention of strings.
cc @acoglio and @moAlobaidi

Update 04_opcodes.md to remove strings

---

documentation/concepts/01_programs.md

This is consistent with a similar change that was agreed upon in another page.

Replace occurrence of 'anonymous' with 'private'.

---

documentation/testnet/public_endpoints/13_records_unspent.md

add documentation on scanning unspent records with snarkOS

---

documentation/aleo/04_opcodes.md

Matches https://github.com/AleoHQ/snarkVM/pull/1656 and https://github.com/AleoHQ/snarkVM/pull/1647.

Update Aleo ins. commit and hash ops.

---

documentation/aleo/04_opcodes.md

This PR closes this [issue](https://github.com/AleoHQ/techops/issues/48)

document new rand.chacha function

---

documentation/aleo/03_language.md

Adds docs for mapping functions `get` `set` `contains` `remove` `get.or_use`
Closes https://github.com/AleoHQ/techops/issues/51

Update aleo instructions mapping docs

---

documentation/concepts/00_accounts.md

I think it looks better this way.
Also auto-removes some trailing whitespace.

Purely cosmetic change.

---

documentation/aleo/04_opcodes.md

This PR closes this [issue](https://github.com/AleoHQ/techops/issues/48).

correct supported types table to support any type

---

documentation/leo/04_operators.md

add block.height opcode to Leo docs

---

documentation/concepts/00_accounts.md

Supersedes https://github.com/AleoHQ/welcome/pull/93.

Clarify counter used to calculate private key.

---

documentation/leo/03_language.md
documentation/leo/04_operators.md

Adds language guides for several of the new Leo features including mapping operations, random functions, hash and commit functions, and block height commands.

Updates to Leo docs

---

documentation/testnet/getting_started/03_deploy_and_execute_demo.md

Fix demo fee amounts

---

documentation/concepts/00_accounts.md

Based on:
- https://github.com/AleoHQ/snarkVM/blob/637e734e19f4b852daae683df4fd36bb17b7fcb9/console/account/src/private_key/try_from.rs#L21
- https://github.com/AleoHQ/snarkVM/blob/637e734e19f4b852daae683df4fd36bb17b7fcb9/console/types/field/src/lib.rs#L59
- https://github.com/AleoHQ/snarkVM/blob/637e734e19f4b852daae683df4fd36bb17b7fcb9/fields/src/traits/prime_field.rs#L104
- https://github.com/AleoHQ/snarkVM/blob/637e734e19f4b852daae683df4fd36bb17b7fcb9/fields/src/traits/prime_field.rs#L79

Fix description of `EncodeToF`.

---

documentation/leo/03_language.md

document leo tuples

---

documentation/leo/03_language.md

document leo constants

---

README.md
documentation/leo/07_resources.md
documentation/sdk/create-aleo-app/01_create_aleo_app.md

c/c : Dead discord link can be hijacked, fixed them to the official one. 
Have a nice evening.
5 most starred Aleo repo should be fixed now

Updated discord link

---

documentation/leo/05_commands.md

[Fix] `leo add`

---

README.md
documentation/00_sdk_overview.md
documentation/concepts/00_accounts.md
documentation/leo/10_auction.md
documentation/sdk/create-aleo-app/01_create_aleo_app.md
documentation/sdk/typescript/00_sdk_overview.md
documentation/sdk/wasm/00_wasm_installation.md
documentation/testnet/getting_started/03_deploy_and_execute_demo.md
documentation/testnet/getting_started/04_developer_toolkit.md

Rename `aleo.tools` to `provable.tools`

---

documentation/leo/16_core_devs_call.md
documentation/leo/17_testnet_beta.md

Updates on 5-17-24.

---

documentation/00_leo_overview.md
documentation/00_overview.md
documentation/aleo/02_hello.md
documentation/aleo/03_language.md
documentation/leo/01_installation.md
documentation/leo/02_hello.md
documentation/leo/03_language.md
documentation/leo/05_commands.md
documentation/leo/16_core_devs_call.md
documentation/leo/17_testnet_beta.md
documentation/sdk/create-aleo-app/01_create_aleo_app.md

[Update] Core Devs Call 5-28-24 and documentation updates.

---

README.md

Discord link was broken(https://aleo.org/discord) changed it to new (https://discord.com/invite/aleo)

Update README.md -Discord link broken

---

documentation/leo/05_commands.md
documentation/leo/16_testnet_beta.md
documentation/sdk/create-leo-app/01_create_leo_app.md
documentation/testnet/getting_started/00_overview.md
documentation/testnet/getting_started/03_deploy_and_execute_demo.md

Updates to relevant docs that reference API and Explorer endpoints

[Update] Documentation for API and Explorer

---

documentation/00_leo_overview.md

Added:
1. Basic bank
2. Vote
3. Token
4. TicTacToe
5. Battleship
https://docs.leo-lang.org/leo

Adding examples for Leo overview page

---

documentation/leo/01_installation.md

Update:
1. Pre-built installer
2. Install from Source
3. Steps for clarity
4. Fixed some styling

Updating Leo installation for prebuilt & install from source & apple silicon

---

documentation/leo/04_operators.md

Update:
1. Language for nor
2. Language for or

Update leo operators language for nor and or

---

documentation/leo/05_commands.md

Update to lower case v in global flags

---

documentation/leo/02_hello.md

Added output explanation for creation of output/ folder after first run

Adding output folder explanation

---

documentation/leo/04_operators.md

Updated neg description to use same terminology with other descriptions

Update neg description

---

documentation/concepts/02_records.md

Update:
1. Consists of
2. If the visibility of the record is private, it is normally encrypted using the owner’s address secret key, to enable privacy in the application.
3. Gates already done
4. Optional already removed.

Update records copy

---

documentation/concepts/01_programs.md

Update:
1. Update to Artifact
2. Update copy for function transfer

Update program copy

---

documentation/leo/09_auction.md

Update:
1. two kinds of parties

Update auction copy

---

documentation/leo/02_hello.md

1. .prover` file to constructing proof, the `.verifier` file to verify proof and the `.avm` file containing the program's bytecode
2. directory changed to build/build

.prover, .verifier, .avm files briefly explained

---

documentation/00_aleo_overview.md
documentation/aleo/02_hello.md

Improves the readability of the Aleo overview and aleo/hello examples

Update Aleo overview and aleo/hello

---

documentation/leo/04_operators.md

1.References provided for mod and rem operations.
2.Rem operation's calculation and explanation included to relevant section

Update rem operation

---

archive/aleo/02_hello.md

Update:
1. Updating language
2. Updating example to sequence

Update aleo hello

---

archive/aleo/03_language.md

Update:
1. fixing arrays to be color_rgb
2. updating red green blue

Update aleo language

---

documentation/language/04_operators.md

updating operators

---

archive/advanced/dive-into-avm/00_overview.md
archive/create-aleo-app/02_create_aleo_app_full.md
archive/src/learn/zkcloud/snarkos_build_guide.md
archive/testnet/getting_started/04_developer_toolkit.md
documentation/guides/02_debuggin.md
documentation/leo_by_example/01_auction.md
documentation/leo_by_example/02_basic_bank.md
documentation/leo_by_example/03_vote.md
documentation/leo_by_example/04_token.md
documentation/leo_by_example/05_tictactoe.md
documentation/leo_by_example/06_battleship.md
documentation/sdk/create-leo-app/01_create_leo_app.md
documentation/sdk/typescript/00_sdk_overview.md
documentation/sdk/wasm/00_wasm_installation.md

This PR updates dead links in the Leo documentation website.

Fixing dead links
