ProvableHQ/leo-docs-source

documentation/developer/language/09_circuits.md

This was discussed on Slack.
The addition clarifies that Leo uses name equivalence of (circuit) types, not structural equivalence.

Clarify name equivalence of circuit types.

---

documentation/developer/language/05_operators.md

Based on a discussion on Slack, my understanding is that (in)equality is supported on all Leo types, including addresses.

Add addresses to types supporting equality.

---

documentation/aleo/concepts/00_accounts.md

This PR updates the documentation for the new account generation model.
`r_pk` is now derived with a `counter`

Update account generation documentation

---

documentation/developer/getting_started/01_installation.md

It looks like `leo` is obsolete (https://crates.io/crates/leo), while the newer one is `leo-lang` (https://crates.io/crates/leo-lang).

Update reference to Leo in crates.io

---

documentation/aleo/concepts/02_records.md

* change "is a that encodes" -> "encodes"

Fixes typo in 02_records.md

---

documentation/developer/language/13_lexical.md

Two pairs of contiguous keywords were not in alphabetical order. This commit puts them in order.
(Side note: the list of keywords is essentially alphabetical, with the slight exceptions that (i) `Self` comes just after `self` in the list and (ii) `i8`, `i16`, ..., `u8`, `u16`, ... are in numeric order. I believe that both exceptions are quite reasonable and make things clearer than following a strictly string-alphabetical order.)

Order some keywords alphabetically

---

documentation/developer/additional_material/00_style.md
documentation/developer/cli/05_test.md
documentation/developer/language/00_flying_tour.md
documentation/developer/language/01_layout.md
documentation/developer/language/11_console.md
documentation/developer/language/12_tests.md
documentation/developer/programming_model/00_model.md

Updates Leo syntax to be up to date with https://github.com/AleoHQ/leo/pull/561

[Grammar] Deprecate context annotation

---

documentation/developer/cli/06_setup.md
documentation/developer/cli/13_publish.md

Follow up on https://github.com/AleoHQ/leo/issues/684
- adds warning - inputs are now being published with source code
- fixes missing colon in `leo setup` - markup broken

[Docs] Few more fixes

---

documentation/developer/language/00_flying_tour.md

Here we are essentially saying 'boolean data type', 'unsigned integer data type', .., 'field data type', 'group (element) data type', ...
So it seems fine to just say 'group'.
Alternatively, '..., field element, group element, ...' if we want to refer to the values of the types. E.g. the boolean type consists of booleans, the field type consists of field elements, the group type consists of group elements.

Nitpicking suggestion for uniformity

---

documentation/developer/language/04_arrays_and_tuples.md

I believe that this was the final agreement on the allowed types for array indices.

Include all the allowed types for array indices.

---

documentation/developer/language/04_arrays_and_tuples.md

As written, it may mislead into thinking that an expression of type `u32` is allowed, as for arrays, but that's not the case for tuples.

Improve description of tuple indices

---

documentation/developer/language/05_operators.md

Since the ordering operators < <= > >= return booleans, but these operators are not defined on booleans, associativity does not really apply to them.
The current grammar rule does not support associations of these operators:
```
ordering-expression = additive-expression
/ additive-expression "<" additive-expression
/ additive-expression ">" additive-expression
/ additive-expression "<=" additive-expression
/ additive-expression ">=" additive-expression
```

Proposed change to table

---

documentation/aleo/concepts/01_programs.md
documentation/developer/additional_material/00_style.md
documentation/developer/language/00_flying_tour.md
documentation/developer/language/01_layout.md
documentation/developer/language/02_variables.md
documentation/developer/language/09_circuits.md
documentation/developer/language/10_imports.md
documentation/developer/toy_examples/02_linear_regression.md

Starting the practice of not pushing directly to master, so that the docs stay reflective of the current released version of Leo.
Changed it here so circuit member variables have semi-colons after them in the documentation.
Adding a tidbit that global constants are now introduced.

Global Consts, Circuit semi-colons

---

documentation/developer/language/05_operators.md

See here: https://developer.aleo.org/developer/language/operators#logical-operators
Note that the Github markdown render does not need this change, this only happens on the docs.
Note: I didn't format the table nicely again.

Fix display of OR operator in docs

---

documentation/developer/language/03_types.md

Note, I do not know how the :::warn works.  It does not render in github markdown, so I can't preview it.  If it does not support bulleted items or hyperlinks, it will need to be restructured.

Add more details on Unicode sequences.

---

documentation/developer/language/03_types.md
documentation/developer/language/04_arrays_and_tuples.md

Closes https://github.com/AleoHQ/leo/issues/985.
Part of Strings epic: https://github.com/AleoHQ/leo/issues/929.
- Adds `char` type description to Leo types.
- Adds string literal to arrays section
- Renames "Arrays and Tuples" -> "Arrays, Strings and Tuples"

Add char and string literal to documentation

---

documentation/developer/language/03_types.md

Type alias documentation. I'm not sure what else to add, but type aliases themselves are fairly straightforward.

type alias documentation

---

documentation/00_getting_started.md
documentation/aleo/08_tooling.md
documentation/concepts/02_records.md
documentation/concepts/03_transactions.md
documentation/concepts/04_transitions.md

- Updated documentation on records (https://github.com/AleoHQ/snarkVM/tree/testnet3/console/program/src/data/record) , specifically the parameters: address of the owner, data, nonce, and added visibility field to table. Also elaborated on section about optional encryption. 
- Updated documentation on transitions (https://github.com/AleoHQ/snarkVM/tree/testnet3/synthesizer/src/block/transition) specifically the parameters: id, program_id, function_name, inputs, outputs, proof, tpk, fee. Added section describing Input (https://github.com/AleoHQ/snarkVM/blob/testnet3/synthesizer/src/block/transition/input/mod.rs) and Output (https://github.com/AleoHQ/snarkVM/tree/testnet3/synthesizer/src/block/transition/output) Records 
- Fixed table on Execute transactions …

Updated records, transitions, and execute transaction 

---

documentation/leo/08_auction.md

This PR removes one line from the Auction instructions for clarity. The deleted line prompts user to "Swap in the private key and address of the auctioneer to program.json." in Step 4, when they just did this in Step 3.

Update 08_auction.md instructions for clarity

---

documentation/leo/03_language.md
documentation/leo/04_operators.md

Closes #191.
Also fixes pre-existing code comments that were out of date.

Document `group::GEN` in Leo.

---

documentation/aleo/03_language.md
documentation/leo/03_language.md

This PR adds documentation for the `get.or_use` opcode in Aleo Instructions and `Mapping::get_or_use` opcode in Leo. As a result, the former `get.or_init` and `Mapping::get_or_init` opcodes are deprecated.
closes #204

[Refactor] Implement get or use opcodes

---

documentation/leo/04_operators.md

add b = 0 field calrfication, and define truncated division for clarity

---

documentation/aleo/03_language.md
documentation/leo/03_language.md

Program IDs are now checked in snarkVM to be lowercase and can contain numbers and underscores.
https://github.com/AleoHQ/snarkVM/pull/1649
closes https://github.com/AleoHQ/techops/issues/44

Update program ID

---

documentation/aleo/06_grammar.md

Also reference ABNF grammar directly in `grammars` repo.
This is just for the high-level (slightly simplified) grammar. The chapter on the ABNF grammar is no updated yet by this PR.

Update high-level grammar of Aleo instructions.

---

documentation/leo/01_installation.md

Aligned with this issue, updating the download links to reflect the new release syntax, i.e., https://github.com/AleoHQ/leo/releases/latest/download/leo.zip

fixing leo download links at documentation/leo/01_installation.md

---

documentation/leo/03_language.md

Provides some documentation for a limitation of bitshift and exponent operators
closes https://github.com/AleoHQ/welcome/issues/276

arithmetic operator rhs must be u8/u16/u32

---

documentation/testnet/getting_started/04_developer_toolkit.md

Fixes the broken link by simply referencing the section above vs. linking to it.

Fix 04_developer_toolkit.md broken link

---

documentation/sdk/create-aleo-app/00_app_installation.md
documentation/sdk/create-aleo-app/01_create_aleo_app.md

1. Added templates and templates to be in combination format (framework + variant)
2. Removed older version of node examples and `--template` options, didn't seem to work when tested locally
3. Adding the "framework + variant" syntax to the tutorial documentation so people aren't confused and can match up what we're using with the tutorial.
4. added faucet by text instructions

Update Create Aleo App Install Script & Tutorial Title

---

documentation/leo/03_language.md
documentation/leo/09_cheatsheet.md

Adds Array Documentation for Leo language docs
Explanation, examples and syntax based on documentation and test cases implemented in https://github.com/AleoHQ/leo/pull/2888

Add Leo Array Syntax Documentation

---

documentation/aleo/03_language.md

document aleo instructions futures and async

---

documentation/sdk/create-aleo-app/01_create_aleo_app.md
documentation/sdk/typescript/00_sdk_overview.md
documentation/sdk/typescript/02_aleo_network_client.md
documentation/testnet/getting_started/02_deploy_and_execute.md
documentation/testnet/getting_started/03_deploy_and_execute_demo.md

There are some remaining references to the old deprecated API scattered in some of the documentation pages.
This PR removes all references to the old API and replaces them with the new api.explorer.aleo.org URL.

Replace all references of vm.aleo.org with the new explorer API

---

documentation/testnet/getting_started/01_installation.md

MacOS is not officially supported for Validators
See: https://github.com/AleoHQ/snarkOS/pull/3040#issuecomment-1913735755

Fixed errror in docs - Section - Installation snarkOS

---

documentation/aleo/07_tooling.md

On https://leo-lang.org/, there are links to download Leo syntax highlighting plugins for Sublime, IntelliJ, and VSCode.
The documentation on how to install these plugins are here: https://developer.aleo.org/leo/tooling
Some of the language and several links were out of date. This PR updates it to the latest.
Separately installed from scratch for all three code editors on MacOSX to test functionality ✅

Plugins for Leo - Documentation Update

---

documentation/leo/05_commands.md

Remove input file references since they have been deprecated

[Fix] Remove input file reference

---

documentation/leo/02_hello.md

Remove input file references, and give description of `program.json`

[Fix] Correct `hello.leo` walkthrough

---

documentation/leo/03_language.md
documentation/leo/04_operators.md
documentation/leo/09_cheatsheet.md
documentation/leo/11_basic_bank.md
documentation/leo/13_token.md
documentation/leo/17_testnet_beta.md

This PR removes the deprecated `finalize` syntax from the docs.

[Update] Remove finalize.

---

documentation/leo/16_core_devs_call.md
documentation/leo/17_testnet_beta.md

Upload 5-21-24 Core Dev Call slides.

---

documentation/leo/17_testnet_beta.md

This should fix deployment issue for both `leo deploy` and `snarkos developer deploy`.

fix: API endpoint should be https

---

documentation/leo/10_auction.md

The doc page is outdated:
1. `testnet3` does not exist, the correct identifier is `testnet`.
2. The `.env` file requires an `ENDPOINT`.  I have configured it to the localhost with a port of `3030`.

docs update: Update Auction doc page to work with latest changes

---

documentation/leo/03_language.md

Left and right sides should agree. Just a minor tweak to the docs.

Fix type mismatch in code example

---

documentation/leo/05_commands.md

Update:
1. Add
2. Deploy
3. Removed red text for `in` and `for`

Update list of commands for add, deploy, and removed red text

---

documentation/leo/03_language.md

const example is added and named as "FOO" like stated in the rest of the docs. The visual is not the best, but the reader will easily understand that FOO is not the input to a function, but a constant which is defined at the beginning.

Constant example added to example program

---

documentation/leo/10_basic_bank.md

Update:
1. Additional
2. Update copy
3. Spelling errors for users and withdrawal

Update basic bank spelling and copy

---

documentation/leo/04_operators.md

1. Example added for sign change: let b: i8 = 64i8.shl_wrapped(2u8); // -128i8
2. Explanation added for the wrapping logic and example case

Explanation added to shl_wrapped

---

documentation/leo/04_operators.md

Explanation added. After testing with non-square numbers, I observed that the operation does not always halt. Instead, execution halts only if the input is not a quadratic residue in the prime field

Updated square_root

---

documentation/leo/04_operators.md

Explanation added as the Schnorr algorithm with an external link to Wikipedia. Suggestions for external link are appreciated.

Short explanation added for signature::verify

---

documentation/testnet/getting_started/01_installation.md

-In Aleo docs, I put requirements separately under each node category depending on what kind of node they are instead of separately categorising them separately under GPU, Storage etc for each node.

docs: make node requirements easier to understand for clients, provers and validators

---

documentation/leo/16_testnet_beta.md

Corrected some spelling errors.

correct spelling errors in program limits section

---

documentation/resources/01_core_devs_call.md

Call was listed as weekly but is actually bi-weekly.

Update Leo Core Devs call to Bi Weekly

---

documentation/sdk/create-leo-app/00_app_installation.md

This PR replaces a reference to `create aleo-app` with the correct command:  `create leo-app` in the online documentation.

Remove reference to `create aleo-app` in Leo lang documentation

---

documentation/cli/04_dependencies.md

This PR adds content to the Leo documentation instructing users how to add dependencies using the Leo CLI.

Leo dependency guide

---

documentation/cli/01_deploying.md
documentation/cli/02_executing.md
documentation/cli/04_dependencies.md
documentation/testing/03_devnet.md

This PR adds content for the `deploy` and `execute` commands in the Leo-lang documentation.  Minor typo fixes to other files are also included.

Update deploy and execute sections

---

documentation/02_where.md
documentation/cli/00_overview.md
documentation/getting_started/03_hello.md
documentation/language/06_programs.md
documentation/leo_by_example/04_token.md
documentation/resources/03_projects.md
documentation/testing/00_overview.md
documentation/testing/02_debugger.md

This PR fixed typos in various spots in the repo.  I ran a spellchecker across all the md files.

Fixing spelling errors

---

documentation/cli/00_overview.md
documentation/cli/01_deploying.md

This PR includes an instruction in the in the Leo CLI overview section to inform users that using the broadcast flag (`-b` or `--broadcast`) is required in order to submit a transaction to a network.

Added comment in Leo execute overview  for broadcast flag

---

documentation/getting_started/02_ide.md
documentation/getting_started/03_hello.md
documentation/language/01_layout.md
documentation/testing/03_devnet.md

This PR fixes a couple minor typos and changes some syntax to improve readability. 
I have also removed two comments stating that the version field in the `program.json` manifest refers to the Leo version used in the project.  Changing the version in this field does not affect compilation.  While it's not ideal to lack documentation regarding the purpose of this field, it is preferable to omit information than to confuse developers

Fixing typos and syntax

---

documentation/testing/01_test_framework.md

This PR adds documentation of the Leo native testing framework.  It should be reviewed (and merged) together with https://github.com/ProvableHQ/leo-examples/pull/8.

Content for native testing framework section of the Leo-lang docs

---

documentation/cli/14_update.md
documentation/getting_started/03_hello.md
documentation/language/01_layout.md

- Module system
- Installing specific versions of Leo from the CLI
- Sidebar on `language/01_layout.md` should now include the following tabs:
- The Manifest
- The Code
- [Optional] Modules

Update docs to be in line with Leo 3.2.0
